
AWSTemplateFormatVersion: "2010-09-09"
Description: Basic stack required for running the ETL POC

Resources:

  RawStageBucket:
    Type: AWS::S3::Bucket    
    Properties:
      BucketName: etl-poc-data-raw
      Tags:
        - Key: stage
          Value: raw

  ArtifactsBucket:
    Type: AWS::S3::Bucket    
    Properties:
      BucketName: etl-poc-artifacts

Outputs:

  RawStageBucketName:
    Description: Name of bucket created for raw etl staging
    Value: !Ref RawStageBucket

  ArtifactsBucketName:
    Description: Name of bucket created for artifacts
    Value: !Ref ArtifactsBucket
