
AWSTemplateFormatVersion: "2010-09-09"
Description: Stack for building the Glue Job for decompressing the data zip.

Parameters:

  ArtifactBucketName:
    Type: String
    MinLength: "1"
    Default: "cf-templates-kzw05u36ei3i-us-east-1"
    Description: "Name of the S3 bucket containing the source code."

  SourceCodeS3Key:
    Type: String
    MinLength: "1"
    Default: "decompress.py"
    Description: "Name of the S3 key of the file with the source code."

Resources:

  GlueJobDecompress:
    Type: AWS::Glue::Job
    Properties:
      Role: !GetAtt GlueJobRole.Arn
      Name: gluejobdecompress
      Command:
        Name: pythonshell
        PythonVersion: 3.9
        ScriptLocation: !Sub "s3://${ArtifactBucketName}/${SourceCodeS3Key}"
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxRetries: 0
      GlueVersion: 3.0
      MaxCapacity: 0.0625

  GlueJobRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - glue.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"

  S3Policy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "s3:DeleteObject",
              "s3:GetObject",
              "s3:PutObject"
              ],
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "logs:CreateLogStream",
              "logs:PutLogEvents"
            ],
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": "logs:CreateLogGroup",
            "Resource": "*"
          }
        ]
      }
      PolicyName: "GlueJobPolicy"
      Roles:
        - !Ref GlueJobRole