
AWSTemplateFormatVersion: 2010-09-09

Description: The CloudFormation template for a set of AWS lambda functions.

Parameters:

  DownloadLambdaFunctionName:
    Type: String
    Description: "Name of the Lambda function that downloads the data zip and uploads to s3."

  ArtifactBucketName:
    Type: String
    MinLength: "1"
    Description: "Name of the S3 bucket containing lambda source .zip files."

  LambdaSourceS3Key:
    Type: String
    MinLength: "1"
    Description: "Name of the S3 key of lambda function .zip file."

  LambdaLayerS3Key:
    Type: String
    MinLength: "1"
    Description: "Name of the S3 key of lambda layer .zip file."


Resources:

  DownloadLambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"

  S3Policy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "s3:DeleteObject",
              "s3:GetObject",
              "s3:PutObject"
              ],
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "logs:CreateLogStream",
              "logs:PutLogEvents"
            ],
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": "logs:CreateLogGroup",
            "Resource": "*"
          }
        ]
      }
      PolicyName: "DownloadLambdaPolicy"
      Roles:
        - !Ref DownloadLambdaExecutionRole

  DownloadLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "download"
      Description: "Downloads data zip from source and uploads it to S3."
      Handler: "download.lambda_handler"
      Role: !GetAtt DownloadLambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref ArtifactBucketName
        S3Key: !Ref LambdaSourceS3Key
      Timeout: 180 #seconds
      MemorySize: 128 #MB
      Runtime: python3.9
      Layers:
        - !Ref libs
    DependsOn:
      - DownloadLambdaExecutionRole
      
  libs:
    Type: "AWS::Lambda::LayerVersion"
    Properties:
      LayerName: blank-python-lib
      Description: Dependencies for the blank-python sample app.
      Content:
        S3Bucket: !Ref ArtifactBucketName
        S3Key: !Ref LambdaLayerS3Key
      CompatibleRuntimes:
        - python3.9
